# Generated by Django 3.2 on 2022-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('hashtags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/posts/%Y/%m/%d/')),
                ('likes', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
